baseURL = "https://creadapte.onrender.com/"
languageCode = "fr-fr"
paginate = 6
theme = "portio"
title = "Créadapte"
DefaultContentLanguage = "fr"

# Main Menu
[[menu.main]]
name = "Accueil"
url = "#home"
weight = 1
[[menu.main]]
name = "A propos"
url = "#about"
weight = 2
[[menu.main]]
name = "Services"
url = "#service"
weight = 3
[[menu.main]]
name = "Créations"
url = "#portfolio"
weight = 4
# [[menu.main]]
# name = "Resume"
# url = "#resume"
# weight = 5
# [[menu.main]]
# name = "Blog"
# url = "#blog"
# weight = 6
[[menu.main]]
name = "Contact"
url = "#contact"
weight = 7

# Sitemap Menu
# [[menu.sitemap]]
# name = "A propos"
# url = "about"
# weight = 1
# [[menu.sitemap]]
# name = "Frequently Ask Question"
# url = "#"
# weight = 2
# [[menu.sitemap]]
# name = "Privacy & Policy"
# url = "#"
# weight = 3
# [[menu.sitemap]]
# name = "Latest Article"
# url = "#"
# weight = 4

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "All right reserved copyright © Portio 2020"
formspreeURL = "YOUR FORMSPREE URL"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/logo.png"
footerLogo = "images/contact/logo.png"

[params.address]
address = "6 rue gounod, 85000 La roche sur yon"
email = "creadapte@gmail.fr"
# openingHours = "Open from 10am to 6pm (close at 5pm Sundays)"
phone = "(+33) 06 60 43 27 02"

[params.map]
APIkey = "YOUR GOOGLE MAP API"
latitude = "23.7783741"
longitude = "90.3746808"
pinImage = "images/pin.png"

# Social icons
[[params.social]]
icon = "fa-facebook-official"
url = "https://www.facebook.com/Cr%C3%A9adapte-100729675024529"
weight = 1
# [[params.social]]
# icon = "fa-linkedin-square"
# url = "https://www.linkedin.com/"
# weight = 2
# [[params.social]]
# icon = "fa-pinterest-square"
# url = "https://www.pinterest.com/"
# weight = 3
# [[params.social]]
# icon = "fa-twitter-square"
# url = "https://twitter.com/"
# weight = 4

